version: '3.3'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - "80:80"
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: qweasdzxc
            MYSQL_DATABASE: db_coba
            MYSQL_USER: user_db
            MYSQL_PASSWORD: qweasd
        ports:
            - "9906:3306"
